#!/usr/bin/env bash

FGGreen="\e[32m"
FGYellow="\e[33m"
FGBlue="\e[34m"
FGMagenta="\e[35m"
RESET="\e[0m"

TARGET=
VERSION="1.0.0"
BASE_PATH="$HOME/.codepm"
CONFIG_PATH="$BASE_PATH/settings.json"
CATEGORIES=
BASE_EXTENSIONS=
BASE_PROJECT_EXTENSIONS=

usage() {
  echo -e "\
Visual Studio Code Profile Manager $FGYellow$VERSION$RESET

Usage: ${FGGreen}codepm$RESET ${FGYellow}[options]$RESET ${FGYellow}[command]$RESET ${FGYellow}[options]$RESET $FGMagenta<path>$RESET

${FGYellow}Commands:$RESET
  ${FGBlue}n  new$RESET          Create a new profile
  ${FGBlue}rm remove$RESET       Remove a profile
  ${FGBlue}ls list$RESET         List all profiles
  ${FGBlue}s setup$RESET         Set default configuration (if not exists) and install dependencies
  ${FGBlue}c category$RESET      Create, update and delete categories

${FGYellow}Options:$RESET
  -c --category   Category of the profile
  -n --name       Name of the profile
  -p --project    Open editor in project mode
  -v --version    Print version
  -h --help       Print usage.


$(new_usage)


$(remove_usage)


$(list_usage)


$(category_usage)\
"
}

new_usage() {
  echo -e "\
${FGBlue}new$RESET Usage: ${FGGreen}codepm$RESET ${FGBlue}new$RESET ${FGYellow}[options]$RESET $FGMagenta<name>$RESET
  
${FGBlue}new$RESET ${FGYellow}Options:$RESET
  -c --category   Category of the profile
  -h --help       Print ${FGBlue}new$RESET usage\
"
}

remove_usage() {
  echo -e "\
${FGBlue}remove$RESET Usage: ${FGGreen}codepm$RESET ${FGBlue}remove$RESET ${FGYellow}[options]$RESET $FGMagenta<name>$RESET
  
${FGBlue}remove$RESET ${FGYellow}Options:$RESET
  -c --category   Category of the profile
  -h --help       Print ${FGBlue}remove$RESET usage\
"
}

list_usage() {
  echo -e "\
${FGBlue}list$RESET Usage: ${FGGreen}codepm$RESET ${FGBlue}list$RESET ${FGYellow}[options]$RESET $FGMagenta<name>$RESET
  
${FGBlue}list$RESET ${FGYellow}Options:$RESET
  -c --category   Category of the profile
  -h --help       Print ${FGBlue}list$RESET usage\
"
}

category_usage() {
  echo -e "\
${FGBlue}category$RESET Usage: ${FGGreen}codepm$RESET ${FGBlue}category$RESET ${FGYellow}[options]$RESET ${FGYellow}[command]$RESET
  
${FGYellow}${FGBlue}category$RESET Commands:$RESET
  ${FGBlue}n new$RESET           Create a new category
  ${FGBlue}u update$RESET        Update a category
  ${FGBlue}r remove$RESET        Remove a category
  ${FGBlue}l list$RESET          List all categories

${FGBlue}category$RESET ${FGYellow}Options:$RESET
  -h --help       Print ${FGBlue}category$RESET usage\
"
}

code() {
  local PPATH="$BASE_PATH/$1/$2"
  local PPATH_DATA="$PPATH/data"
  local PPATH_EXTS="$PPATH/exts"
  /usr/bin/env code --max-memory 2048 --locale en-US --sync off --extensions-dir "$PPATH_EXTS" --user-data-dir "$PPATH_DATA"
}

install_extension() {
  local PPATH="$BASE_PATH/$1/$2"
  local PPATH_DATA="$PPATH/data"
  local PPATH_EXTS="$PPATH/exts"
  /usr/bin/env code --extensions-dir "$PPATH_EXTS" --user-data-dir "$PPATH_DATA" --install-extension "$3"
}

disable_extension() {
  local PPATH="$BASE_PATH/$1/$2"
  local PPATH_DATA="$PPATH/data"
  local PPATH_EXTS="$PPATH/exts"
  /usr/bin/env code --extensions-dir "$PPATH_EXTS" --user-data-dir "$PPATH_DATA" --disable-extension "$3"
}

select_category() {
  PS3='Select category: '
  select opt in "${CATEGORIES[@]}"; do
    case $opt in
    *)
      if [[ -n "$opt" ]]; then
        echo "$opt"
        return
      fi
      ;;
    esac
  done
  PS3=
}

select_profile() {
  PS3='Select profile: '
  local options=()
  for p in "$BASE_PATH/$1"/*; do
    options+=("$(basename "$p")")
  done

  select opt in "${options[@]}"; do
    case $opt in
    *)
      if [[ -n "$opt" ]]; then
        echo "$opt"
        return
      fi
      ;;
    esac
  done
  PS3=
}

read_name() {
  local NAME=
  read -p "Enter name: " -r NAME
  echo "$NAME"
}

read_category() {
  local NAME=
  read -p "Enter category: " -r NAME
  echo "$NAME"
}

print_category_profiles() {
  echo -e "$FGBlue$1$RESET profiles":
  local values=("$BASE_PATH/$1"/*)
  for p in "${values[@]}"; do
    echo -n -e "$FGYellow"
    if [[ "$p" == "${values[-1]}" ]]; then
      printf ' └ '
    elif [[ "$p" == "${values[0]}" ]]; then
      printf ' ┌ '
    else
      printf ' ├ '
    fi
    echo -n -e "$RESET"
    basename "$p"
  done
}

new() {
  local CATEGORY=
  local NAME=

  while true; do
    if [[ -z "$1" ]]; then
      break
    fi

    case "$1" in
    -h | --help)
      echo -e "Visual Studio Code Profile Manager ${FGYellow}$VERSION$RESET"
      echo
      new_usage
      return
      ;;
    -c | --category)
      if [[ "$2" == -* ]]; then
        shift
      else
        if [[ "${CATEGORIES[*]}" =~ $2 ]]; then
          CATEGORY="$2"
        fi
        shift 2
      fi
      ;;
    *)
      if [[ "$1" != -* ]] && [[ -z "$NAME" ]]; then
        NAME="$1"
        shift
      else
        shift
        if [[ "$1" != -* ]] && [[ -n "$NAME" ]]; then
          shift
        fi
      fi
      ;;
    esac
  done

  if [[ -z "$CATEGORY" ]]; then
    CATEGORY=$(select_category)
  fi

  if [[ -z "$NAME" ]]; then
    NAME=$(read_name)
  fi

  local PPATH="$BASE_PATH/$CATEGORY/$NAME"
  local PPATH_DATA="$PPATH/data"
  local PPATH_EXTS="$PPATH/exts"

  mkdir -p "$PPATH"
  mkdir -p "$PPATH_DATA"
  mkdir -p "$PPATH_EXTS"

  local EXTENSIONS=("${BASE_EXTENSIONS[@]}" "${BASE_PROJECT_EXTENSIONS[@]}")

  for e in "${EXTENSIONS[@]}"; do
    install_extension "$CATEGORY" "$NAME" "$e"
  done
}

remove() {
  local CATEGORY=
  local NAME=

  while true; do
    if [[ -z "$1" ]]; then
      break
    fi

    case "$1" in
    -h | --help)
      echo -e "Visual Studio Code Profile Manager $FGYellow$VERSION$RESET"
      echo
      remove_usage
      return
      ;;
    -c | --category)
      if [[ "$2" == -* ]]; then
        shift
      else
        if [[ "${CATEGORIES[*]}" =~ $2 ]]; then
          CATEGORY="$2"
        fi
        shift 2
      fi
      ;;
    *)
      if [[ "$1" != -* ]] && [[ -z "$NAME" ]]; then
        NAME="$1"
        shift
      else
        shift
        if [[ "$1" != -* ]] && [[ -n "$NAME" ]]; then
          shift
        fi
      fi
      ;;
    esac
  done

  if [[ -z "$CATEGORY" ]]; then
    CATEGORY=$(select_category)
  fi

  if [[ -z "$NAME" ]]; then
    NAME=$(select_profile "$CATEGORY")
  fi

  local PPATH="$BASE_PATH/$CATEGORY/$NAME"
  rm -rf "$PPATH"

  if [[ -z "$(ls -A "$BASE_PATH/$CATEGORY")" ]]; then
    rmdir "$BASE_PATH/$CATEGORY" 1>/dev/null
  fi
}

list() {
  local CATEGORY=

  while true; do
    if [[ -z "$1" ]]; then
      break
    fi

    case "$1" in
    -h | --help)
      echo -e "Visual Studio Code Profile Manager ${FGYellow}$VERSION$RESET"
      echo
      list_usage
      return
      ;;
    -c | --category)
      if [[ "$2" == -* ]]; then
        shift
      else
        if [[ "${CATEGORIES[*]}" =~ $2 ]]; then
          CATEGORY="$2"
        fi
        shift 2
      fi
      ;;
    *) shift ;;
    esac
  done

  if [[ -n "$CATEGORY" ]]; then
    if [[ ! -d "$BASE_PATH/$CATEGORY" ]] || [[ ! "$(ls -A "$BASE_PATH/$CATEGORY")" ]]; then return; fi
    print_category_profiles "$CATEGORY"
  else
    local values=("$BASE_PATH"/*)
    if [[ -z "$(ls -A "$BASE_PATH")" ]]; then return; fi
    for c in "${values[@]}"; do
      if [[ ! -d "$BASE_PATH/$(basename "$c")" ]] || [[ ! "$(ls -A "$BASE_PATH/$(basename "$c")")" ]]; then continue; fi
      print_category_profiles "$(basename "$c")"
      if [[ "$c" != "${values[-1]}" ]]; then
        echo
      fi
    done
  fi
}

main() {
  local PROJECT=false
  local TARGET_PATH=
  local CATEGORY=
  local NAME=

  while true; do
    if [[ -z "$1" ]]; then
      break
    fi

    case "$1" in
    -h | --help)
      usage
      return
      ;;
    -v | --version)
      echo "$VERSION"
      return
      ;;
    -p | --project)
      PROJECT=true
      shift
      ;;
    -c | --category)
      if [[ "${CATEGORIES[*]}" =~ $2 ]]; then
        CATEGORY="$2"
      fi
      shift 2
      ;;
    -n | --name)
      NAME="$2"
      shift 2
      ;;
    *)
      if [[ "$1" != -* ]] && [[ -z "$TARGET_PATH" ]]; then
        TARGET_PATH="$1"
        shift
      else
        shift
        if [[ "$1" != -* ]] && [[ -n "$TARGET_PATH" ]]; then
          shift
        fi
      fi
      ;;
    esac
  done

  if [[ -z "$CATEGORY" ]]; then
    CATEGORY=$(select_category)
  fi

  if [[ -z "$NAME" ]]; then
    NAME=$(select_profile "$CATEGORY")
  fi

  if [[ ! -d "$BASE_PATH/$CATEGORY/$NAME" ]]; then
    echo -e "Profile $FGMagenta$NAME$RESET does not exist in category $FGMagenta$CATEGORY$RESET"
    exit 1
  fi

  code "$CATEGORY" "$NAME"
}

setup() {
  EXTS=()
  which jq >/dev/null || EXTS+=("jq")
  if [[ -n "${EXTS[*]}" ]]; then
    case "$TARGET" in
    darwin) brew install "${EXTS[*]}" ;;
    debian) apt install "${EXTS[*]}" ;;
    archlinux) pacman -S "${EXTS[*]}" ;;
    *) echo -e "Please install ${FGGreen}jq$RESET manually" ;;
    esac
  fi

  local DEFAULT_BASE_EXTENSIONS=(
    "teabyii.ayu"
    "aaron-bond.better-comments"
    "usernamehw.errorl"
    "mkxml.vscode-filesize"
    "miguelsolorio.fluent-icons"
    "christian-kohler.path-intellisense"
    "miguelsolorio.symbols"
    "wayou.vscode-todo-highlight"
  )
  local DEFAULT_BASE_PROJECT_EXTENSIONS=(
    "mikestead.dotenv"
    "editorconfig.editorco"
    "ultram4rine.vscode-choosealicense"
    "donjayamanne.githist"
    "codezombiech.gitig"
    "eamodio.gitlens"
    "yzhang.markdown-all-in-one"
    "bierner.markdown-mermaid"
    "DavidAnson.vscode-markdownlint"
    "jock.svg"
    "SimonSiefke.svg-preview"
  )

  if [[ ! -d "$BASE_PATH" ]]; then mkdir -p "$BASE_PATH"; fi
  if [[ ! -f "$CONFIG_PATH" ]]; then echo "{}" >"$CONFIG_PATH"; fi
  jq --arg BASE_EXTENSIONS "${DEFAULT_BASE_EXTENSIONS[*]}" \
    'if (has("BASE_EXTENSIONS") | not) or (.BASE_EXTENSIONS | length == 0 )
     then setpath(["BASE_EXTENSIONS"]; $BASE_EXTENSIONS | split(" ")) 
     else . end' <"$CONFIG_PATH" >/tmp/settings.json && mv /tmp/settings.json "$CONFIG_PATH"

  jq --arg BASE_PROJECT_EXTENSIONS "${DEFAULT_BASE_PROJECT_EXTENSIONS[*]}" \
    'if (has("BASE_PROJECT_EXTENSIONS") | not) or (.BASE_PROJECT_EXTENSIONS | length == 0 )
     then setpath(["BASE_PROJECT_EXTENSIONS"]; $BASE_PROJECT_EXTENSIONS | split(" ")) 
     else . end' <"$CONFIG_PATH" >/tmp/settings.json && mv /tmp/settings.json "$CONFIG_PATH"

}

category() {
  CATEGORY=$2
  NAME=$3
  case "$1" in
  n | new)
    if [[ -z "$CATEGORY" ]]; then
      CATEGORY=$(read_category)
    fi
    mkdir -p "$BASE_PATH/$CATEGORY"
    ;;
  u | update)
    if [[ -z "$CATEGORY" ]]; then
      CATEGORY=$(select_category)
    fi
    if [[ -z "$NAME" ]]; then
      NAME=$(read_category)
    fi
    mv "$BASE_PATH/$CATEGORY" "$BASE_PATH/$NAME"
    ;;
  r | remove)
    if [[ -z "$CATEGORY" ]]; then
      CATEGORY=$(select_category)
    fi
    rm -rf "$BASE_PATH/${CATEGORY:?}"
    ;;
  l | list)
    echo "${CATEGORIES[*]}"
    ;;
  -h | --help)
    echo -e "Visual Studio Code Profile Manager ${FGYellow}$VERSION$RESET"
    echo
    category_usage
    ;;
  *)
    echo -e "Visual Studio Code Profile Manager ${FGYellow}$VERSION$RESET"
    echo
    category_usage
    ;;
  esac
}

# Ensure all dependencies are installed
if [[ "$1" != 's' ]] && [[ "$1" != 'setup' ]]; then
  which code >/dev/null || {
    echo -e "Please install ${FGGreen}code$RESET manually or try with ${FGGreen}codepm$RESET ${FGBlue}setup$RESET"
    exit 1
  }
  which jq >/dev/null || {
    echo -e "Please install ${FGGreen}jq$RESET manually or try with ${FGGreen}codepm$RESET ${FGBlue}setup$RESET"
    exit 1
  }

  read -r -a CATEGORIES <<<"$(find "$BASE_PATH" -type d -depth 1 | xargs basename -a | xargs)"

  read -r -a BASE_EXTENSIONS <<<"$(jq -r '@sh "\(.BASE_EXTENSIONS)"' <"$CONFIG_PATH")"
  if [[ "${BASE_EXTENSIONS[*]}" == "null" ]]; then BASE_EXTENSIONS=(); fi

  read -r -a BASE_PROJECT_EXTENSIONS <<<"$(jq -r '@sh "\(.BASE_PROJECT_EXTENSIONS)"' <"$CONFIG_PATH")"
  if [[ "${BASE_PROJECT_EXTENSIONS[*]}" == "null" ]]; then BASE_PROJECT_EXTENSIONS=(); fi
fi

case $(uname) in
'Darwin') TARGET=darwin ;;
'Linux')
  which apt && TARGET=debian
  which pacman && TARGET=archlinux
  ;;
esac

if [[ -z "$1" ]]; then
  usage
  exit 0
fi

case "$1" in
n | new)
  shift
  new "$@"
  ;;
rm | remove)
  shift
  remove "$@"
  ;;
ls | list)
  shift
  list "$@"
  ;;
s | setup)
  shift
  setup
  ;;
c | category)
  shift
  category "$@"
  ;;
*) main "$@" ;;
esac
